export enum EnvField {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  MONGODB_URI = 'MONGODB_URI',
  MONGOLAB_URI = 'MONGOLAB_URI',
  RAVEN_LINK = 'RAVEN_LINK',
  SENTRY_RELEASE = 'SENTRY_RELEASE',
  REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET',
  JWT_SECRET = 'JWT_SECRET',
  FACEBOOK_ID = 'FACEBOOK_ID',
  FACEBOOK_SECRET = 'FACEBOOK_SECRET',
  FACEBOOK_TEST_USER_TOKEN = 'FACEBOOK_TEST_USER_TOKEN',
  FIREBASE_FILE = 'FIREBASE_FILE',
  FIREBASE_URL = 'FIREBASE_URL',
  FIREBASE_BUCKET = 'FIREBASE_BUCKET'
}
