export enum EnvField {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  MONGODB_URI = 'MONGODB_URI',
  MONGOLAB_URI = 'MONGOLAB_URI',
  RAVEN_LINK = 'RAVEN_LINK',
  REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET',
  JWT_SECRET = 'JWT_SECRET',
  FACEBOOK_ID = 'FACEBOOK_ID',
  FACEBOOK_SECRET = 'FACEBOOK_SECRET'
}
