export enum DebtsStatus {
    CREATION_AWAITING = 'CREATION_AWAITING',
    UNCHANGED = 'UNCHANGED',
    CHANGE_AWAITING = 'CHANGE_AWAITING',
    USER_DELETED = 'USER_DELETED',
    CONNECT_USER = 'CONNECT_USER'
}
